# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=258)),
                ('criteria', models.CharField(max_length=100)),
                ('in_danger', models.BooleanField(default=False)),
                ('http_url', models.CharField(max_length=258)),
                ('image_url', models.CharField(max_length=258)),
                ('iso_code', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=2056)),
                ('states', models.CharField(max_length=512)),
                ('transboundary', models.CharField(max_length=128)),
                ('unique_number', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('cultural', models.BooleanField(default=False)),
                ('natural', models.BooleanField(default=False)),
                ('mixed', models.BooleanField(default=False)),
                ('delisted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
