# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20170203_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.CharField(max_length=48),
        ),
    ]
